Users/Areas/Admin/Controllers/ContentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Users.Infrastructure;
using Users.Models;
using Users.Models.Entities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace Users.Areas.Admin.Controllers
{
    public class ContentController : Controller
    {
        //
        // GET: /Admin/Content/
        string username;

        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }

        private AppRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppRoleManager>();
            }
        }
        IRepo myrepo;
        public ContentController(IRepo repopara)
        {
            myrepo = repopara;
           
        }
        public ActionResult Index()
        {
            return View(myrepo.Contents);
        }
        public ActionResult Edit(int IdContent)
        {
            Content mycontent = myrepo.Contents.FirstOrDefault(x => x.IdContent == IdContent);

            ViewBag.catelist = new SelectList(myrepo.Categories.Select(x => new { x.Idcategory, x.Catename }), "Idcategory", "Catename", 1);

            ViewBag.subcatelist = new SelectList(myrepo.Subcategories.Select(x => new { x.IdSubcategory, x.Subcatename }), "IdSubcategory", "Subcatename", 1);

                return View(mycontent);


        }
        [HttpPost]
        public ActionResult Edit(Content Contentpara, HttpPostedFileBase image = null)
        {
           

            if(ModelState.IsValid)
            {
                if (image != null)
                {
                    Contentpara.ImageType = image.ContentType;
                    Contentpara.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(Contentpara.ImageData, 0, image.ContentLength);
                    myrepo.AddContent(Contentpara);

                }
                else
                {
                    myrepo.AddContent(Contentpara);
                }


                return RedirectToAction("Index");
            }
            else
            {
                return View(Contentpara);
            }
        }
        [Authorize]
        [HttpPost]
        public ActionResult Create(Content contentpara, HttpPostedFileBase image = null)
        {
            if (HttpContext.User.Identity.IsAuthenticated == true)
            {
                username = HttpContext.User.Identity.Name;
            }
            
            if(ModelState.IsValid)
            {
                contentpara.UserId = UserManager.FindByName(username).Id;
                contentpara.Seo = contentpara.Title.GenerateSlug();
            
            if (image != null)
            {
                contentpara.ImageType = image.ContentType;
                contentpara.ImageData = new byte[image.ContentLength];
                image.InputStream.Read(contentpara.ImageData, 0, image.ContentLength);
                myrepo.AddContent(contentpara);


            }
            else
            {
                myrepo.AddContent(contentpara);
            }
            }

            return RedirectToAction("Index");

        }
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.catelist = new SelectList(myrepo.Categories.Select(x => new { x.Idcategory, x.Catename }), "Idcategory", "Catename", 1);

            ViewBag.subcatelist = new SelectList(GetSubCategories(1).Select(x => new { x.IdSubcategory, x.Subcatename }), "IdSubcategory", "Subcatename", 1);
            //ViewBag.catelist = new SelectList(myrepo.Categories.Select(x => new { x.Idcategory, x.Catename }), "Idcategory", "Catename", 1);

            //ViewBag.subcatelist = new SelectList(myrepo.Subcategories.Select(x => new { x.IdSubcategory, x.Subcatename }), "IdSubcategory", "Subcatename", 1);
            return View(new Content());

        }
        public ActionResult Test()
        {
            ViewBag.catelist = new SelectList(myrepo.Categories.Select(x => new { x.Idcategory, x.Catename }), "Idcategory", "Catename", 1);

            ViewBag.subcatelist = new SelectList(GetSubCategories(1).Select(x=> new {x.IdSubcategory,x.Subcatename}), "IdSubcategory", "Subcatename", 1);
            
            //Content mycontent = myrepo.Contents.FirstOrDefault(x => x.IdContent == 1);
            //int? idcategory = 0;
            //int? idsubcategory = 0;

            //string namecategory, namesubcategory;
            //int? SelectedIdCatSubCat = mycontent.idcatsubcat;
            //if (SelectedIdCatSubCat != null)
            //{
            //    int idcatsubcat = (int)SelectedIdCatSubCat;
            //    idcategory = myrepo.CatSubCats.Where(x => x.idcatsubcat == idcatsubcat).Select(x => x.Idcategory).FirstOrDefault();
            //    idsubcategory = myrepo.CatSubCats.Where(x => x.idcatsubcat == idcatsubcat).Select(x => x.IdSubcategory).FirstOrDefault();


            //}

            //namecategory = myrepo.Categories.Where(x => x.Idcategory == idcategory).Select(x => x.Catename).FirstOrDefault();
            //namesubcategory = myrepo.Subcategories.Where(x => x.IdSubcategory == idsubcategory).Select(x => x.Subcatename).FirstOrDefault();

            //SelectList categorylist = new SelectList(myrepo.Categories.ToList());


            //ViewBag.catelist = new SelectList( myrepo.Categories.Select(x => new { x.Idcategory,x.Catename}),"Idcategory","Catename",2);
            //ViewBag.listest = new SelectList(new[] { "Duoc lam", "kha lam", "Good job" });

            return View();

        }
[HttpGet]
        public JsonResult LoadSubCate(int idcate)
        {
            var listSubcate = GetSubCategories(idcate);
            var listsubcate = listSubcate.Select(m => new SelectListItem { Text = m.Subcatename, Value = m.IdSubcategory.ToString() });

            return Json(listsubcate, JsonRequestBehavior.AllowGet);

        }

        
        public IEnumerable<Subcategory> GetSubCategories(int idcategory)
        {
            int?[] idsub = myrepo.CatSubCats.Where(x => x.Idcategory == idcategory).Select(x => x.IdSubcategory).ToArray();


            IEnumerable<Subcategory> mysubcate = myrepo.Subcategories.Where(x => idsub.Contains(x.IdSubcategory));

            return mysubcate;
        }
        public Category getCategory(int idsubcate)
        {
            int? idcate= myrepo.CatSubCats.Where(x => x.IdSubcategory == idsubcate).Select(x => x.Idcategory).First();

            return myrepo.Categories.Where(x => x.Idcategory == idcate).First();


        }
        public FileContentResult GetImage(int IdContent)
        {
            Content mycontent = myrepo.Contents
                .FirstOrDefault(p => p.IdContent == IdContent);
            if (mycontent != null)
            {
                return File(mycontent.ImageData, mycontent.ImageType);
            }
            else
            {
                return null;
            }
        }
        public ActionResult Upload()
        {
            var file = Request.Files["Filedata"];
            string savePath = Server.MapPath(@"~\Content\" + file.FileName);
            file.SaveAs(savePath);

            return Content(Url.Content(@"~\Content\" + file.FileName));
        }

        public ActionResult Delete(int idcontent)
        {
            myrepo.DeleteContent(idcontent);
            return RedirectToAction("Index");

        }
	}
}

Users/Areas/Admin/Views/Content/Create.cshtml
@model Users.Models.Entities.Content

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
    <!-- TinyMCE Script Reference -->
<script src="~/scripts/tinymce/tinymce.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<script src="~/Content/uploadify/jquery.uploadify.js"></script>
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/Uploadify/uploadify.css")" />
<!-- Script to wire up your TinyMCE editor -->
<script type="text/javascript">
    tinyMCE.init({
        // General options
        mode: "textareas",
        //theme: "simple",
        // Theme options
        //toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"


    });
    
</script>
<script type="text/javascript">
        $(function () {
            $('#file_upload').uploadify({
                'swf': '@Url.Content("~/Content/Uploadify/uploadify.swf")',
                'cancelImg': '~/Content/Uploadify/uploadify-cancel.png',
                'uploader': '@Url.Action("Upload", "Content")',
                'onUploadSuccess': function (file, data, response) {
                    alert('The file ' + file.name + ' was successfully uploaded with a response of ' + response + ':' + data);
                    var img = "<img style = 'height:80px;width:80px' src = '" + data + "' />";
                    $("#uploaded").append("<img src='" + data + "' alt='Uploaded Image' />");
                    tinyMCE.activeEditor.execCommand("mceInsertContent", true, img);
                }

            });
        });
</script>
<script type="text/javascript">
    {
        $(document).ready(function () {
            $("#Category").change(

                function () {
                    alert("Hello changed");
                    var currentidcate = $(this).val();
                    alert(currentidcate);
                    var link = "LoadSubCate?idcate=" + currentidcate;
                    alert(link);
                    $.getJSON(link, function (itemData) {

                        var select = $("#IdSubcategory");
                        select.empty();
                        alert(itemData[0].Text);
                        $.each(itemData, function (index, data) {

                            select.append($('<option/>', {
                                value: data.Value,
                                text: data.Text
                            }))
                        });

                    });
                });
        })
    }
</script>





<h2>Create</h2>


<div class="panel">
    <div class="panel-heading">
        <h3>Edit @Model.Title</h3>
    </div>

    @using (Html.BeginForm("Create", "Content",
        FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="panel-body">
            @Html.HiddenFor(m => m.IdContent)
            <div class="form-group">
                <div>

                    @Html.DropDownList("Category", (SelectList)ViewBag.catelist)
                    @Html.DropDownList("IdSubcategory", (SelectList)ViewBag.subcatelist)


                </div>
                </div>

                <div class="form-group">
                    <label>Title</label>
                    @Html.TextBox("Title", null, new { @class="form-control"})

                </div>
                <div class="form-group">
                    <label>Byline</label>
                    @Html.TextBox("Byline", null, new { @class = "form-control" })

                </div>
                <div class="form-group">
                    <label>Teaser</label>
                    @Html.TextBox("Teaser", null, new { @class = "form-control"})

                </div>
                <div class="form-group">
                    <label>Body</label>


                    @Html.TextArea("Body", null, new { @class = "form-control", rows = 20 })
                    <div>
                        Select Images to upload.
                        <input type="file" name="file_upload" id="file_upload" />
                    </div>
                    <div id="uploaded">
                    </div>

                </div>
                <div class="form-group">
                    <label>TagLine</label>
                    @Html.TextBox("TagLine", null, new { @class = "form-control"})

                </div>
                <div class="form-group">
                    <label>Creation Date</label>
                    @Html.TextBox("CreationDate", @DateTime.Now.ToShortDateString(), new { @class = "form-control" })

                </div>
                <div class="form-group">
                    <label>Updated Date</label>
                    @Html.TextBox("UpdatedDate", @DateTime.Now.ToShortDateString(), new { @class = "form-control" })

                </div>

                <div class="form-group">
                    <div style="position:relative;">
                        <label>Image</label>
                        <a class='btn' href='javascript:;'>
                            Choose File...
                            <input type="file" name="Image" size="40"
                                   style="position:absolute;z-index:2;top:0;
                            left:0;filter: alpha(opacity=0); opacity:0;
                            background-color:transparent;color:transparent;"
                                   onchange='$("#upload-file-info").html($(this).val());'>
                        </a>
                        <span class='label label-info' id="upload-file-info"></span>
                    </div>
                    @if (Model.ImageData == null)
                {
                <div class="form-control-static">No Image</div>
                }
                else
                {
                <img class="img-thumbnail" width="150" height="150"
                     src="@Url.Action("GetImage", "Content",
                        new { Model.IdContent })" />
                }
                </div>
            </div>

        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null, new
       {
           @class = "btn btn-default"
       })
        </div>
    }
</div>

Users/Areas/Admin/Views/Content/Edit.cshtml
@model Users.Models.Entities.Content

@{
    ViewBag.Title = "Create";

    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<script src="~/scripts/tinymce/tinymce.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<script src="~/Content/uploadify/jquery.uploadify.js"></script>
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/Uploadify/uploadify.css")" />
<!-- Script to wire up your TinyMCE editor -->
<script type="text/javascript">
    tinyMCE.init({
        // General options
        mode: "textareas",
        //theme: "simple",
        // Theme options
        //toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"


    });

</script>
<script type="text/javascript">
        $(function () {
            $('#file_upload').uploadify({
                'swf': '@Url.Content("~/Content/Uploadify/uploadify.swf")',
                'cancelImg': '~/Content/Uploadify/uploadify-cancel.png',
                'uploader': '@Url.Action("Upload", "Content")',
                'onUploadSuccess': function (file, data, response) {
                    alert('The file ' + file.name + ' was successfully uploaded with a response of ' + response + ':' + data);
                    var img = "<img style = 'height:80px;width:80px' src = '" + data + "' />";
                    $("#uploaded").append("<img src='" + data + "' alt='Uploaded Image' />");
                    tinyMCE.activeEditor.execCommand("mceInsertContent", true, img);
                }

            });
        });
</script>

<div class="panel">
    <div class="panel-heading">
        <h3>Edit @Model.Title</h3>
    </div>

    @using (Html.BeginForm("Create", "Content",
        FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="panel-body">
            @Html.HiddenFor(m => m.IdContent)
            <div class="form-group">
                <label>Title</label>
                @Html.TextBoxFor(m=>m.Title, new { @class = "form-control" })

            </div>
            <div class="form-group">
                <label>Byline</label>
                @Html.TextBoxFor(m => m.Byline, new { @class = "form-control" })

            </div>
            <div class="form-group">
                <label>Teaser</label>
                @Html.TextBoxFor(m => m.Teaser, new { @class = "form-control"})

            </div>
            <div class="form-group">
                <label>Body</label>
                @Html.TextAreaFor(m=>m.Body, new { @class = "form-control", rows = 20 })
                <div>
                    Click Select files to upload files.
                    <input type="file" name="file_upload" id="file_upload" />
                </div>
                <div id="uploaded">
                </div>
            </div>
            <div class="form-group">
                <label>TagLine</label>
                @Html.TextBoxFor(m => m.TagLine, new { @class = "form-control"})

            </div>
            <div class="form-group">
                <label>Creation Date</label>
                @Html.TextBoxFor(m => m.CreationDate, new { @class = "form-control" })

            </div>
            <div class="form-group">
                <label>Updated Date</label>
                @Html.TextBoxFor(m => m.UpdatedDate, new { @class = "form-control" })

            </div>

            <div class="form-group">
                <div style="position:relative;">
                    <label>Image</label>
                    <a class='btn' href='javascript:;'>
                        Choose File...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                            left:0;filter: alpha(opacity=0); opacity:0;
                            background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">No Image</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Content",
                        new { Model.IdContent })" />
                }
            </div>
        </div>

        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null, new
       {
           @class = "btn btn-default"
       })
        </div>
    }
</div>

Users/Areas/Admin/Views/Content/Index.cshtml
@model  IEnumerable<Users.Models.Entities.Content>

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">

        <h2>All Articles</h2>
    </div> 


    <div class="panel-body">
    <table class="table table-striped table-bordered ">
        <tr>
            <th>ID </th>
            <th>Title </th>
            <th>Teaser</th>
            <th>Date Creation</th>
            <th>Date Modified</th>
            <th>Action</th>
        </tr>
        @foreach(var item in Model)
        {
            <tr>
                <td class="text-center">@item.IdContent</td>
                <td class="text-center">@Html.ActionLink(item.Title,"Edit", new {item.IdContent})</td>
                <td class="text-center">@item.Teaser</td>
                <td class="text-right">@item.CreationDate</td>
                <td class="text-right">@item.UpdatedDate</td>
                <td class="text-center">@Html.ActionLink("Delete", "Delete", new { idcontent=item.IdContent})</td>
            </tr>
        }
        </table>
        <div class="panel-footer">
            @Html.ActionLink("Add new article", "Create", FormMethod.Post, new  { @class="btn btn-default"})
        </div>
    </div>


</div>

Users/Areas/Admin/Views/Content/Test.cshtml
@using Users.Models.Entities
@{
    ViewBag.Title = "Test";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="~/Content/uploadify/jquery.uploadify.js"></script>

<script type="text/javascript">
    {
        $(document).ready(function () {
            $("#Category").change(
                
                function () {
                    alert("Hello changed");
                    var currentidcate = $(this).val();
                    alert(currentidcate);
                    var link = "LoadSubCate?idcate=" + currentidcate;
                    alert(link);
                    $.getJSON(link, function (itemData) {

                           var select = $("#Subcategory");
                           select.empty();
                           alert(itemData[0].Text);
                           $.each(itemData, function (index, data) {
                               
                               select.append($('<option/>', {
                                   value: data.Value,
                                   text: data.Text
                               }))
                           });
                           
                       });
            });
        })
    }
</script>
        <h2>Test</h2>
<script type="text/javascript">
        $(function () {
            $('#file_upload').uploadify({
                'swf': '@Url.Content("~/Content/Uploadify/uploadify.swf")',
                'cancelImg': '~/Content/Uploadify/uploadify-cancel.png',
                'uploader': '@Url.Action("Upload", "Content")',
                'onUploadSuccess' : function(file, data, response) {
                     $("#uploaded").append("<img src='" + data + "' alt='Uploaded Image' />");
                }

            });
        });
</script>
        <div>

        @Html.DropDownList("Category", (SelectList)ViewBag.catelist)
            @Html.DropDownList("Subcategory", (SelectList)ViewBag.subcatelist)


</div>

<div>
    Click Select files to upload files.
    <input type="file" name="file_upload" id="file_upload" />
</div>
<div id="uploaded">
</div>