Users/Areas/Admin/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Users.Models.Entities;
using Users.Infrastructure;
using Users.Models;

namespace Users.Areas.Admin.Controllers
{
    public class SettingController : Controller
    {
        //
        // GET: /Admin/Setting/
        IRepo myrepo;
        Settings mysetting;
        public SettingController(IRepo repopara)
        {
            myrepo = repopara;
        }

        [HttpGet]
        public ActionResult Index()
        {
            mysetting = myrepo.LoadSetting();
            ViewBag.SiteName=mysetting.General.SiteName;
            ViewBag.AdminEmail=mysetting.General.AdminEmail;
            ViewBag.MetaDesc=mysetting.Seo.HomeMetaDescription;
            ViewBag.MetaTitle=mysetting.Seo.HomeMetaTitle;

            return View();
                        
        }
        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            Settings xsetting = myrepo.LoadSetting();
                xsetting.General.SiteName = form["SiteName"].ToString();

                xsetting.General.AdminEmail = form["AdminEmail"].ToString();
                xsetting.Seo.HomeMetaDescription = form["MetaDesc"].ToString();

               xsetting.Seo.HomeMetaTitle = form["MetaTitle"].ToString();
                xsetting.Save();

            

            return View();
        }
        

	}
}

Users/Areas/Admin/Views/Setting/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Settings Index</h2>
@using(Html.BeginForm("Index","Setting",FormMethod.Post))
{
    <label>General Settings</label>
    <div class="form-group">
        <label> Site Name</label>
        <br />
        <textarea name="SiteName">@ViewBag.SiteName</textarea>   
             <br />
        <label> Admin Email</label>
        <br />
        <textarea name="AdminEmail">@ViewBag.AdminEmail</textarea>
    </div>
    <div class="form-group">
        <label> Seo Settings</label>
        <div class="form-group">
            <label>Home meta Description</label>
            <textarea name="MetaDesc">@ViewBag.MetaDesc</textarea>
            <br />
            <label> Home meta tile</label>
            <textarea name="MetaTitle">@ViewBag.MetaTitle</textarea>
        </div>
    </div>
            <div class="panel-footer">
              
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null, new
       {
           @class = "btn btn-default"
       }
       )
        </div>
}