Users/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Users.Models.Entities;
using Users.Infrastructure;
namespace Users.Controllers
{
    public class NavController : Controller
    {
        public IRepo myrepo;

        public NavController(IRepo repo)
        {
            this.myrepo = repo;
        }
        //
        // GET: /Nav/
        //list all menu
        public PartialViewResult Menu()
        {
            //replace by repo by another repo. IE categories

            MenuTree myparent = new MenuTree(myrepo);




            return PartialView("FlexMenu", myparent);
        }
        public PartialViewResult BottomMenu()
        {
            //replace by repo by another repo. IE categories

            MenuTree myparent = new MenuTree(myrepo);




            return PartialView("BottomFlexMenu", myparent);
        }
	}
}

Users/Views/Shared/Article.cshtml
@model Users.Models.Entities.Content


    <div class="col-sm-4">
        <div class="panel panel-default">
            <div class="panel-body color">
                
                @*<span class="glyphicon glyphicon-search"></span>*@
                <div class="row"> 
                <div class="col-lg-2"><span class="glyphicon glyphicon-search"></span></div>
                <div class="col-lg-10 text-right">@Model.CreationDate</div>
                </div>
                <h4 class="text-center">@Html.RouteLink(@Model.Title, "Article", new { idcontent = Model.IdContent, slug=Model.Seo })  </h4>
                <p class="text-left">@Model.Teaser ...</p>
                <p class="text-center">@Html.RouteLink("Learn more", "Article", new { idcontent = Model.IdContent, slug=Model.Seo }, new { @class="btn btn-info"})</p>
            </div>
            
        </div>
    </div>
    

Users/Views/Shared/OneArticle.cshtml
@model Users.Models.Entities.Content



<div class="row">
    <div class="col-lg-2"><a href="~/"> <span class="glyphicon glyphicon-backward"></span></a></div>
    <div class="col-lg-10 text-right">@Model.CreationDate</div>
</div>
            <h2 class="text-center">@Html.RouteLink(@Model.Title,"Article",  new { idcontent = Model.IdContent }) </h2>
<p>@Model.Teaser</p>
            <p>@Html.Raw(@Model.Body)</p>
<p class="text-right"><span>@Model.TagLine</span><span>Views: @Model.ViewCount</span></p>

Users/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null) {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

Users/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <style>
        .container { padding-top: 10px; }
        .validation-summary-errors { color: #f00; }
    </style>
</head>
<body class="container">
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>

Users/Views/Shared/_LayoutArticle.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/bootstrap-theme.css">
    <script src="~/Content/jquery-1.11.2.min.js"></script>

    <script src="~/Content/bootstrap.min.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />


    <meta name="description" content="@ViewBag.HomeSeoMeta">
    <meta name="author" content="@ViewBag.AdminEmail">

    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <style>
        .navbar-header {
            float: left;
            padding: 15px;
            text-align: center;
            width: 100%;
        }

        .navbar-brand {
            float: none;
        }
    </style>
</head>
<body>
    <nav class="nav navbar-inverse" id="main-nav">
        <div class="container">
            <div class="navbar-header">
                <a href="~/" class = "navbar-brand" >Alumc.com</a>

            </div>
        </div> <!-- end container -->

    </nav>


    <!-- Body -->
    @*<section>
            <hr>
            <div class="jumbotron">
                <div class="container text-center">
                    <div class="row">

                        <div class="col-lg-12">This is great blog</div>

                    </div> <!--end div row -->
                </div> <!--end div container -->
            </div> <!-- end div jumbo -->
        </section>*@


    <section>
        <!-- section articles -->
        <div class="container">
            @*<div class="page-header">
                <small>This is the lastest articles from our website</small>
            </div>*@

            <div class="row">
                <div class="col-lg-12">
                    @RenderBody()
                </div>
            </div> <!-- end row -->

        </div>

    </section>

    <!-- FOOTER -->

    <footer>
        <hr>

        <div class="container text-left">

            <div class="row">
                <div class="col-lg-4">
                    <h3>Links</h3>
                    <ul>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Facebook</a></li>
                    </ul>
                </div>
                <div class="col-lg-4">
                    <h3>Categories</h3>
                    <div>
                        @Html.Action("BottomMenu", "Nav")
                    </div>
                </div>
                <div class="col-lg-4">
                    <h3>Member</h3>

                    @Html.Action("LoginBox", "Account")
                </div>
            </div>


            <hr>



            <p>&copy; Copyright 2014.</p>
        </div> <!-- end container -->

    </footer>
    <!-- end container -->
</body>

</html>

Users/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/bootstrap-theme.css">
    <script src="~/Content/jquery-1.11.2.min.js"></script>

    <script src="~/Content/bootstrap.min.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />


    <meta name="description" content="@ViewBag.HomeSeoMeta">
    <meta name="author" content="@ViewBag.AdminEmail">

    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <style>
        .navbar-header {
            float: left;
            padding: 15px;
            text-align: center;
            width: 100%;
        }

        .navbar-brand {
            float: none;
        }
    </style>
</head>
<body>
    <nav class="nav navbar-inverse" id="main-nav">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Alumc.com", "Main", null, new { @class = "navbar-brand" })
                <span class="navbar-link">

                    @Html.Action("Menu", "Nav")

                </span>
            </div>
     
        </div> <!-- end container -->

    </nav>


    <!-- Body -->
    @*<section>
        <hr>
        <div class="jumbotron">
            <div class="container text-center">
                <div class="row">

                    <div class="col-lg-12">This is great blog</div>

                </div> <!--end div row -->
            </div> <!--end div container -->
        </div> <!-- end div jumbo -->
    </section>*@


    <section>
        <!-- section articles -->
        <div class="container">
            <div class="page-header">
                <small>This is the lastest articles from our website</small>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    @RenderBody()
                </div>
            </div> <!-- end row -->

        </div>

    </section>

    <!-- FOOTER -->

    <footer>
        <hr>

        <div class="container text-left">

            <div class="row">
                <div class="col-lg-4">
                    <h3>Links</h3>
                    <ul>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Facebook</a></li>
                    </ul>
                </div>
                <div class="col-lg-4">
                    <h3>Categories</h3>
                    <div>
                        @Html.Action("BottomMenu", "Nav")
                    </div>
                </div>
                <div class="col-lg-4">
                    <h3>Member</h3>

                    @Html.Action("LoginBox","Account")
                </div>
            </div>


            <hr>



            <p>&copy; Copyright 2014.</p>
        </div> <!-- end container -->

    </footer>
     <!-- end container -->
</body>

</html>